# Yarn 2 / Berry configuration file, see https://yarnpkg.com/configuration/yarnrc for documentation.
defaultSemverRangePrefix: ''
supportedArchitectures:
  os:
    - 'darwin'
    - 'linux'
  cpu:
    - 'current'
    - 'x86'
